### ISSUE TITLE
Side bar posts

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#176]
![untitled-1](https://cloud.githubusercontent.com/assets/17341325/21150606/490315d2-c168-11e6-8ed2-91a652208279.jpg)

**Comment by nirgn975** [comment]
The bug is in the spinner. As you can see the game is not loading, and there is the "Continue with Facebook" button, and not "Share on Facebook" or "Try again". So the game is good, but the spinner is the problem..

**To my future self:** try the set the spinner variable to `false` in `onDestroy` life cycle hook (set it to `false` in `onInit` can work too, needs to think which is better).
